### PR TITLE
V1 model inference with NAIP

### PR DESCRIPTION
**Pull request by lillythomas**
The purpose of this PR is to create a notebook demonstrating how to run inference on new NAIP scenes. It may also serve the purpose of demonstrating sim search with the generated embeddings.

### CODE REVIEW

**Comment by lillythomas** [comment]
Some current examples of similarity search results generated with 3600~ embeddings from NAIP sized at 256x256 and the `v0.5.3/mae_v0.5.3_epoch-08_val-loss-0.3150.ckpt` checkpoint.

Screenshot 2024-05-10 at 11 44 27 AM
Screenshot 2024-05-10 at 11 43 02 AM

Screenshot 2024-05-10 at 11 42 00 AM

Screenshot 2024-05-10 at 11 42 39 AM

Screenshot 2024-05-10 at 11 42 25 AM
Screenshot 2024-05-10 at 11 48 44 AM

Screenshot 2024-05-10 at 11 48 16 AM

These are all from the Bay area of California in 2020. Kind of crazy that it even captures similarity between open ocean surfaces with specifically visible white capping.

The notebook in this PR can be run to reproduce.

**Comment by yellowcap** [comment]
@lillythomas I think this is a great example, and I think we should polish this up and add to the tutorials. I wanted to ask if you would be up for using `stacchip` for the data generation in the example 😊 . I made some small changes to stacchip to make it easier to use. Creating naip tiles is now just a few lines of code, see https://clay-foundation.github.io/stacchip/naip-tutorial/ .

**Comment by lillythomas** [comment]
@yellowcap sounds good! I'll work on swapping the method for getting NAIP chips to use stacchip and request your review on it.

**Review by yellowcap — APPROVED** [review]
Almost there! Just a few small comments, mainly cosmetic things. Feel free to merge when updated.

- Register new notebook to `_toc.yml`
- add `lancedb` to pip install
- The cell where chips are downloaded is duplicated, remove older version
- Update relative paths to `../..` (notebook requires to levels down)
- Centroid extraction can be simplified:
Replace
```
    lon, lat = box(
        bounding_box[0], bounding_box[1], bounding_box[2], bounding_box[3]
    ).centroid.coords[0]
```
with
```
    lon, lat = bounding_box.centroid.coords[0]
```

**Pull request merged**
