### PR TITLE
More detailed image plots

### PR DESCRIPTION
**Pull request by brunosan**
This changes create a more detailed Image log, with the actual RGB, <IR>, <SAR> and DEM.

It also chooses the most likely item of the first 3 batches to have structure (max stdev), and plots all bands, the predictions and the differences, like this

image

### CODE REVIEW

**Comment by alkalait** [comment]
Hello! Where can I find a how-to on reading these plots?

**Comment by brunosan** [comment]
Hi @alkalait ! I don't actually think this will get merged, but here's a description of what you see.

The code picks the item on the first 3 batches with most stdev as a proxy for features within.

Each Clay has many spectral bands, so the plot tries to see what's being learned by displaying the RGB as a color image, then the average of all red edge, Infrareds, SAR and the elevation model (all this on the top row).

the middle row has the output as the model learns to reconstruct the image. Random at first, and ideally ends up being the same as the input.

The bottom row is just the normalized difference.

In a ideal world, the middle row goes from random to the same as the first row, as the bottom row becomes grey (no difference). Hope it helps.

**Comment by alkalait** [comment]
That helps, thanks @brunosan. Based on what you said, in this particular instance the model is not doing well at reconstructing the patches. Am I reading it correctly?

**Comment by brunosan** [comment]
Indeed. I did not leave it long, but yes, the reconstruction is not even close. 
You basically need to leave it longer on training, but are also tracking a potential issue on #156.

**Comment by yellowcap** [comment]
We plan to implement RGB plots for the v1 output, we are not planning to update v0 ouptut at this point anymore.

**Pull request closed without merging**
